### ISSUE TITLE
 Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ghost** [biopet/gtftorefflat#9]
Having the following issue after the installation according to manual.

```
 java -jar GtftoRefflat-assembly-0.1.jar -g ~/gtf/Macaca_mulatta.Mmul_10.102.gtf -r Mmul_10.refflat -R ~/MMulReference/Macaca_mulatta.Mmul_10.dna_sm.primary_assembly.concatenated.fa
INFO  [2021-06-04 09:37:48,659] [GtftoRefflat$] - Start
Exception in thread "main" java.lang.UnsupportedClassVersionError: htsjdk/samtools/reference/FastaSequenceFile : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at nl.biopet.utils.ngs.fasta.package$.getDictFromFasta(package.scala:42)
        at nl.biopet.utils.ngs.fasta.package$.getCachedDict(package.scala:64)
        at nl.biopet.tools.gtftorefflat.GtftoRefflat$$anonfun$3.apply(GtftoRefflat.scala:59)
        at nl.biopet.tools.gtftorefflat.GtftoRefflat$$anonfun$3.apply(GtftoRefflat.scala:59)
        at scala.Option.map(Option.scala:146)
        at nl.biopet.tools.gtftorefflat.GtftoRefflat$.gtfToRefflat(GtftoRefflat.scala:59)
        at nl.biopet.tools.gtftorefflat.GtftoRefflat$.main(GtftoRefflat.scala:40)
        at nl.biopet.tools.gtftorefflat.GtftoRefflat.main(GtftoRefflat.scala)

```

**Comment by DavyCats** [comment]
This tools is no longer maintained. If you want to convert GTF files to Refflat, I'd recommand using the UCSC's gtfToGenePred program and then converting this genePred file to Refflat. This can be done using a command like this:
```bash
gtfToGenePred \
    -genePredExt \
    your_gtf_file.gtf \
    /dev/stdout | \
    awk 'BEGIN { OFS="\t"} {print $12, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' \
    > your_refflat_file.refflat
```

gtfToGenePred can be easily installed using conda: https://anaconda.org/bioconda/ucsc-gtftogenepred.

I hope this helps!
